apiVersion: v1
kind: Service
metadata:
  name: eventuate-local-cdc-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    svc: eventuate-local-cdc-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eventuate-local-cdc-service
  labels:
    application: pms
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        svc: eventuate-local-cdc-service
    spec:
      containers:
      - name: eventuate-local-cdc-service
        image: gcr.io/spartan-thunder-272123/cdc:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          # name: httpport
        command: ["bash", "-c", "java -Dsun.net.inetaddr.ttl=30 -jar *.jar" ]
        env:
          # - name: JAVA_OPTS
          #   value: "-Dsun.net.inetaddr.ttl=30 -Dspring.profiles.active=EventuatePolling"
          # - name: SPRING_DATASOURCE_URL
          #   value: jdbc:mysql://pms-mysql/eventuate?autoReconnect=true&useSSL=false
          # - name: SPRING_DATASOURCE_USERNAME
          #   value: root
          # - name: SPRING_DATASOURCE_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: mysql-pass
          #       key: password
          # - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          #   value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: kafka-service:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: zoo1:2181
          # - name: EVENTUATELOCAL_CDC_DB_USER_NAME
          #   value: root
          # - name: EVENTUATELOCAL_CDC_DB_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: mysql-pass
          #       key: password
          # - name: EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH
          #   value: /eventuatelocal/cdc/leader1  
          # - name: "EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH"
          #   value: "/eventuatelocal/cdc/leader/1"
          # - name: "EVENTUATELOCAL_CDC_OFFSET_STORAGE_TOPIC_NAME"
          #   value: "db.history.common"
          # - name: "EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID"
          #   value: "1"
          # - name: "EVENTUATELOCAL_CDC_READER_NAME"
          #   value: "customcdcreader"
          # - name: "EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC"
          #   value: "false"
          # - name: "EVENTUATE_CDC_TYPE"
          #   value: "EventuateTram"
          # - name: "EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME"
          #   value: "MESSAGE"
          # - name: "EVENTUATE_DATABASE_SCHEMA"
          #   value: "eventuate"
          # - name: "SPRING_PROFILES_ACTIVE"
          #   value: "EventuatePolling"
          # - name: EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS
          #   value: "500"
          # - name: EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING
          #   value: "1000"
          # - name: EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING
          #   value: "100"
          # - name: EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS
          #   value: "500"             
---