apiVersion: v1
kind: Service
metadata:
  name: notification-service-load-balance
spec:
  type: LoadBalancer
  ports:
  - name: port-9090
    port: 9090
    protocol: TCP
  selector:
    application: notification-service
      