# apiVersion: v1
# kind: Service
# metadata:
#   name: ftgo-zookeeper
#   labels:
#     name: ftgo-zookeeper
# spec:
#   ports:
#   - port: 2181
#     targetPort: 2181
#   clusterIP: None
#   selector:
#     role: ftgo-zookeeper
# ---
# apiVersion: apps/v1beta1
# kind: StatefulSet
# metadata:
#   name: ftgo-zookeeper
# spec:
#   serviceName: "zookeeper"
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         role: ftgo-zookeeper
#     spec:
#       terminationGracePeriodSeconds: 10
#       containers:
#         - name: ftgo-zookeeper
#           image: eventuateio/eventuateio-local-zookeeper:0.14.0
#           ports:
#               - containerPort: 2181
#           volumeMounts:
#             - name: ftgo-zookeeper-persistent-storage
#               mountPath: /usr/local/zookeeper-data
#   volumeClaimTemplates:
#   - metadata:
#       name: ftgo-zookeeper-persistent-storage
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       resources:
#         requests:
#           storage: 1Gi
# ---
apiVersion: v1
kind: ReplicationController
metadata:
  name:  ftgo-zookeeper
spec:
  replicas: 1
  selector:
    app:  ftgo-zookeeper
  template:
    metadata:
      labels:
        app:  ftgo-zookeeper
    spec:
      containers:
      - name:  ftgo-zookeeper
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER
          value: ftgo-zookeeper
---
kind: Service
apiVersion: v1
metadata:
  name: ftgo-zookeeper
spec:
  type: LoadBalancer
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP 
  - name: port-2888
    port: 2888
    protocol: TCP 
  - name: port-3888
    port: 3888
    protocol: TCP 
  selector:
    app: ftgo-zookeeper         