# apiVersion: v1
# kind: Service
# metadata:
#   name: ftgo-kafka
#   labels:
#     name: ftgo-kafka
# spec:
#   ports:
#   - port: 9092
#     targetPort: 9092
#   selector:
#     role: ftgo-kafka
# ---
# apiVersion: apps/v1beta1
# kind: StatefulSet
# metadata:
#   name: ftgo-kafka
# spec:
#   serviceName: "kafka"
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         role: ftgo-kafka
#     spec:
#       terminationGracePeriodSeconds: 5
#       containers:
#         - name: ftgo-kafka
#           image: eventuateio/eventuateio-local-kafka:latest
#           imagePullPolicy: Always
#           env:
#             - name: KAFKA_HEAP_OPTS
#               value: -Xmx320m -Xms320m
#             - name: ZOOKEEPER_SERVERS
#               value: ftgo-zookeeper:2181
#           ports:
#               - containerPort: 9092
#           volumeMounts:
#             - name: ftgo-kafka-persistent-storage-api
#               mountPath: /usr/local/kafka-data
#             - name: ftgo-kafka-config-volume-api
#               mountPath: /usr/local/kafka-config    
#       volumes:
#       - name: ftgo-kafka-config-volume-api 
#         configMap:
#           name: ftgo-kafka-config
#   volumeClaimTemplates:
#   - metadata:
#       name: ftgo-kafka-persistent-storage-api
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       resources:
#         requests:
#           storage: 1Gi
# ---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ftgo-kafka
spec:
  replicas: 1
  selector:
    app: ftgo-kafka
  template:
    metadata:
      labels:
        app: ftgo-kafka
    spec:
      containers:
      - name: ftgo-kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 172.31.25.198
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: ftgo-zookeeper:2181
---
apiVersion: v1
kind: Service
metadata:
  name: ftgo-kafka
spec:
  type: LoadBalancer
  externalIPs:
    - 172.31.25.198
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: ftgo-kafka
---