apiVersion: v1
kind: Service
metadata:
  name: service-registry-load-balance
spec:
  type: LoadBalancer
  ports:
  - name: port-8761
    port: 8761
    protocol: TCP
  selector:
    application: pm
      