export class APIResponse{
    status:number;
    message:string;
    data:any;
}
export enum APIStatus{
    ERR_INVALID_DATA=100,
    ERR_USER_NOT_EXIST=110,
    ERR_USER_NOT_VALID=111,
    USER_ALREADY_EXIST=112,
    USER_PENDING_STATUS=113,
    INVALID_PARAMETER=200, 
    ERR_UNAUTHORIZED=401,
    ERR_PERMISSION_DENIED=402, 
    // Common status
    OK=200,
    ERR_INTERNAL_SERVER=500, 
    SQL_ERROR=501, 
    ERR_BAD_REQUEST=400, 
    ERR_SESSION_DATA_INVALID=603,
    ERR_SESSION_NOT_FOUND=604, 
    
    //User status
    ERR_USER_NOT_FOUND=404, 
    ERR_USER_ADDRESS_NOT_FOUND=405,
    ERR_GET_LIST_USERS=406, 
    ERR_MISSING_PASSWORD=407, 
    ERR_UNCORRECT_PASSWORD=408,
}