server:
  port: 8000
zuul:
  routes:
    authentication:
      path: /authentication/**
      serviceId: AUTH_SERVICE
      strip-prefix: false
    project:
      path: /project/**
      serviceId: PROJECT_SERVICE
      strip-prefix: false
    task:
      path: /task/**
      serviceId: TASK_SERVICE
      strip-prefix: false
  ignored-services: '*'
endpoints:
  trace:
    sensitive: false   
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/  
      